services:
  payload-template:
    image: ghcr.io/m6o4solutions/payload-template-project:latest
    container_name: payload-template
    restart: unless-stopped
    networks:
      - traefik-network
    env_file:
      - stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payload-template.rule=Host(`payload-template.m6o4solutions.com`)"
      - "traefik.http.routers.payload-template.entrypoints=websecure"
      - "traefik.http.routers.payload-template.tls.certresolver=letsencrypt"
      - "traefik.http.services.payload-template.loadbalancer.server.port=3000"

networks:
  traefik-network:
    external: true
    name: traefik-network
